services:
  backend:
    build: ./server
    ports:
      - "5001:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=5000

  frontend:
    build: ./client
    ports:
      - "5174:5173"

    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
